name: run_simulation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Setting up the worker, installing system dependencies, and ROS (Linux)
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - uses: ros-tooling/setup-ros@0.0.16
        with:
          required-ros-distributions: melodic dashing
      - run: "source /opt/ros/dashing/setup.bash && ros2 run --help"
      - run: "source /opt/ros/melodic/setup.bash && rosnode --help"
