name: run_simulation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Setting up the worker, installing system dependencies, and ROS (Linux)
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: ros-tooling/setup-ros@0.0.20
        with:
          required-ros-distributions: melodic
      - run: "source /opt/ros/melodic/setup.bash && export ROS_PYTHON_VERSION=3 && mkdir -p ~/raceon_sim_ws/src && cd ~/raceon_sim_ws && catkin_make"
      - run: "source ~/raceon_sim_ws/devel/setup.bash && sudo apt-get install ros-melodic-ros-control ros-melodic-gazebo-ros-control ros-melodic-ros-controllers python3-opencv ros-melodic-ackermann-msgs python3-empy && pip3 install pynput"
