name: run_simulation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Setting up the worker, installing system dependencies, and ROS (Linux)
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: ros-tooling/setup-ros@0.0.20
        with:
          required-ros-distributions: melodic #dashing
#      - run: "source /opt/ros/dashing/setup.bash && ros2 run --help"
      - run: "source /opt/ros/melodic/setup.bash && rosnode --help"
